### ISSUE TITLE
open-vm-tools power-on issue

### ISSUE THREAD

**Issue by izenk** [vmware/open-vm-tools#354]
```
vCloud Director 9.1
Ubuntu Server 16.04.1 x64
open-vm-tools 2:10.2.0-3~ubuntu0.16.04.1
cloud-init 19.1-1-gbaa47854-0ubuntu1~16.04.1
```

Cloudinit is configured to work with open-vm-tools [(KB)](https://kb.vmware.com/s/article/59557)

As I understand, vmware tools during first boot copies some file (like cust.cfg) to special cloud-init temp dir, from which cloud init reads network config and starts later customization.
While first boot is always fine, issues appears with second and later boots.

I use 'Static - IP Pool' for vms network.
First boot finishes normal in terms of network configuration.
Then if I stop/start vm from vcloud web UI, cloud-init can't to find cust.cfg, because open-vm-tools does not prepare it - as a result cloud-init fails to get network config and fails-back to default config (which is dhcp) - what lead to such situation:
in vcloud web UI vm is displayed as 'Powered on' with some 'Static IP Pool'  address, but in reality it has another ip got from dhcp.

cloud-init.log for second boot, when issues occures
```
2019-07-23 13:21:09,257 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned VMware Virtual Platform
2019-07-23 13:21:09,258 - DataSourceOVF.py[DEBUG]: VMware Virtualization Platform found
2019-07-23 13:21:09,258 - DataSourceOVF.py[DEBUG]: Found the customization plugin at /usr/lib/open-vm-tools/plugins/vmsvc/libdeployPkgP
lugin.so
2019-07-23 13:21:09,258 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:14,263 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:19,269 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:24,275 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:29,278 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:34,282 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:39,286 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:44,290 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:49,295 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:54,298 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:21:59,303 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:22:04,309 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:22:09,312 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:22:14,317 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:22:19,323 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:22:24,329 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:22:29,335 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:22:34,340 - DataSourceOVF.py[DEBUG]: Waiting for VMware Customization Config File
2019-07-23 13:22:39,346 - util.py[DEBUG]: waiting for configuration file took 90.088 seconds
2019-07-23 13:22:39,347 - DataSourceOVF.py[DEBUG]: Did not find VMware Customization Config File
2019-07-23 13:22:39,347 - util.py[DEBUG]: Running command ['vmware-rpctool', 'info-get guestinfo.ovfEnv'] with allowed return codes [0]
 (shell=False, capture=True)
2019-07-23 13:22:39,353 - handlers.py[DEBUG]: finish: init-local/search-OVF: FAIL: no local data found from DataSourceOVF
2019-07-23 13:22:39,353 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVF'> failed
2019-07-23 13:22:39,356 - util.py[DEBUG]: Getting data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVF'> failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 733, in find_source
    if s.update_metadata([EventType.BOOT_NEW_INSTANCE]):
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 622, in update_metadata
    result = self.get_data()
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 256, in get_data
    return_value = self._get_data()
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceOVF.py", line 245, in _get_data
    (md, ud, cfg) = read_ovf_environment(contents)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceOVF.py", line 394, in read_ovf_environment
    props = get_properties(contents)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceOVF.py", line 553, in get_properties
    raise XmlError("No 'PropertySection's")
cloudinit.sources.DataSourceOVF.XmlError: No 'PropertySection's
2019-07-23 13:22:39,390 - main.py[DEBUG]: No local datasource found
```

toolsDeployPkg.log for first boot. No logs for other boots - seem it was not ran.
```
## Starting deploy pkg operation
Deploying /tmp/vmware-root/49e575d3/cust7029933098505202199.cab
Initializing deployment module.

Cleaning old state file from tmp directory.

EXIT STATE INPROGRESS

Setting deploy error: Error removing lock /tmp/.vmware-deploy.INPROGRESS (No such file or directory)

EXIT STATE Done

Setting deploy error: Error removing lock /tmp/.vmware-deploy.Done (No such file or directory)

EXIT STATE ERRORED

Setting deploy error: Error removing lock /tmp/.vmware-deploy.ERRORED (No such file or directory)

Setting deploy error: Success.

Deploying cabinet file /tmp/vmware-root/49e575d3/cust7029933098505202199.cab.

Transitioning from state (null) to state INPROGRESS.

ENTER STATE INPROGRESS

Reading cabinet file /tmp/vmware-root/49e575d3/cust7029933098505202199.cab.

Flags in the header: 0

Original deployment command: /usr/bin/perl -I/tmp/.vmware/linux/deploy/scripts /tmp/.vmware/linux/deploy/scripts/Customize.pl /tmp/.vmware/linux/deploy/cust.cfg

Actual deployment command: /usr/bin/perl -I/tmp/.vmware-imgcust-dZMKDmP/scripts /tmp/.vmware-imgcust-dZMKDmP/scripts/Customize.pl /tmp/.vmware-imgcust-dZMKDmP/cust.cfg

Extracting package files.

Check if cust.cfg exists.
cust.cfg is found in '/tmp/.vmware-imgcust-dZMKDmP' directory.
Command to exec : /usr/bin/cloud-init

sizeof ProcessInternal is 56

Returning, pending output from stdout
Returning, pending output from stderr
Saving output from stdout
Process exited normally after 2 seconds, returned 0
No more output from stdout
No more output from stderr
Customization command output: /usr/bin/cloud-init 19.1-1-gbaa47854-0ubuntu1~16.04.1


cloud-init is installed
Checking if cloud.cfg exists and if cloud-init is enabled.
Executing cloud-init workflow
Creating temp directory /var/run/vmware-imc to copy customization files
Command to exec : /bin/mkdir

sizeof ProcessInternal is 56

Returning, pending output from stdout
Returning, pending output from stderr
Process exited normally after 0 seconds, returned 0
No more output from stdout
No more output from stderr
Customization command output:

Check if nics.txt exists. Copy if exists, skip otherwise
Command to exec : /usr/bin/test

sizeof ProcessInternal is 56

Returning, pending output from stdout
Returning, pending output from stderr
Process exited normally after 0 seconds, returned 1
No more output from stdout
No more output from stderr
Customization command output:

Check if custom script(pre/post customization) exists.
Copying main configuration file cust.cfg
Command to exec : /bin/cp

sizeof ProcessInternal is 56

Returning, pending output from stdout
Returning, pending output from stderr
Process exited normally after 0 seconds, returned 0
No more output from stdout
No more output from stderr
Customization command output:

Command to exec : /bin/mv

sizeof ProcessInternal is 56

Returning, pending output from stdout
Returning, pending output from stderr
Process exited normally after 0 seconds, returned 0
No more output from stdout
No more output from stderr
Customization command output:

Deployment for cloud-init succeeded.
Transitioning from state INPROGRESS to state Done.

ENTER STATE Done

EXIT STATE INPROGRESS

Launching cleanup.

Command to exec : /bin/rm

sizeof ProcessInternal is 56

Returning, pending output from stdout
Returning, pending output from stderr
Process exited normally after 0 seconds, returned 0
No more output from stdout
No more output from stderr
Customization command output:

sSkipReboot: true, forceSkipReboot false

Ran DeployPkg_DeployPackageFromFile successfully
## Closing log
```

**Comment by PengpengSun** [comment]
@izenk 
This is a known cloud-init issue. 
And you are right about on the second and later boot, cloud-init will revert network back to default which is DHCP.  Currently you have to disable cloud-init by adding /etc/cloud/cloud-init.disabled file after the first boot, or you can remove "disable_vmware_customization: false" from /etc/cloud/cloud.cfg file, with this cloud-init should also be disabled since no datasource found.

There is a LaunchPad bug I filed to cloud-init, https://bugs.launchpad.net/cloud-init/+bug/1835205, maybe you can add your log to it if you have an LaunchPad account.

**Comment by izenk** [comment]
@PengpengSun thanks

Posted to https://bugs.launchpad.net/cloud-init/+bug/1835205

This one can be closed
